
package client.server;


import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CampusService", targetNamespace = "http://server/", wsdlLocation = "file:/Users/t_chaml/drrsWS/CampusClientApplication/src/client/campus.wsdl")
public class CampusService
    extends Service
{

    private final static URL CAMPUSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CAMPUSSERVICE_EXCEPTION;
    private final static QName CAMPUSSERVICE_QNAME = new QName("http://server/", "CampusService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/t_chaml/drrsWS/CampusClientApplication/src/client/campus.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CAMPUSSERVICE_WSDL_LOCATION = url;
        CAMPUSSERVICE_EXCEPTION = e;
    }

    public CampusService() {
        super(__getWsdlLocation(), CAMPUSSERVICE_QNAME);
    }

    public CampusService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CAMPUSSERVICE_QNAME, features);
    }

    public CampusService(URL wsdlLocation) {
        super(wsdlLocation, CAMPUSSERVICE_QNAME);
    }

    public CampusService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CAMPUSSERVICE_QNAME, features);
    }

    public CampusService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CampusService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServerServerInterface
     */
    @WebEndpoint(name = "KKLCampusServerPort")
    public ServerServerInterface getKKLCampusServerPort() {
        return super.getPort(new QName("http://server/", "KKLCampusServerPort"), ServerServerInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerServerInterface
     */
    @WebEndpoint(name = "KKLCampusServerPort")
    public ServerServerInterface getKKLCampusServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "KKLCampusServerPort"), ServerServerInterface.class, features);
    }

    /**
     * 
     * @return
     *     returns ServerServerInterface
     */
    @WebEndpoint(name = "WSTCampusServerPort")
    public ServerServerInterface getWSTCampusServerPort() {
        return super.getPort(new QName("http://server/", "WSTCampusServerPort"), ServerServerInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerServerInterface
     */
    @WebEndpoint(name = "WSTCampusServerPort")
    public ServerServerInterface getWSTCampusServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "WSTCampusServerPort"), ServerServerInterface.class, features);
    }

    /**
     * 
     * @return
     *     returns ServerServerInterface
     */
    @WebEndpoint(name = "DVLCampusServerPort")
    public ServerServerInterface getDVLCampusServerPort() {
        return super.getPort(new QName("http://server/", "DVLCampusServerPort"), ServerServerInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerServerInterface
     */
    @WebEndpoint(name = "DVLCampusServerPort")
    public ServerServerInterface getDVLCampusServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "DVLCampusServerPort"), ServerServerInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CAMPUSSERVICE_EXCEPTION!= null) {
            throw CAMPUSSERVICE_EXCEPTION;
        }
        return CAMPUSSERVICE_WSDL_LOCATION;
    }

}
